GET https://api.jikan.moe/v4/seasons/now
GET https://aniwatch-api-v1-0.onrender.com/api/search/my+deer+friend/1
GET https://aniwatch-api-v1-0.onrender.com/api/episode/oshi-no-ko-season-2-19256
GET https://consumet-luffer-anime.vercel.app/anime/gogoanime/Oshi no ko?page=1
GET https://consumet-luffer-anime.vercel.app/anime/gogoanime/info/oshi-no-ko-2nd-season
GET https://consumet-luffer-anime.vercel.app/anime/gogoanime/watch/oshi-no-ko-2nd-season-episode-1?server=gogocdn
GET https://consumet-luffer-anime.vercel.app/anime/crunchyroll/info?id=G9VHN9PK3&mediaType=movie
GET https://consumet-luffer-anime.vercel.app/meta/anilist/demon
GET https://gelbooru.com/index.php?page=post&s=list&tags=all
GET https://gelbooru.com/index.php?page=dapi&s=post&q=index&json=1&tags=oshi_no_ko&pid=1
GET https://gelbooru.com/index.php?page=dapi&s=tag&q=index&json=1&name_pattern=%tokidoki_bosotto_roshia-go_de_dereru_tonari_no_alya-san%
GET https://gelbooru.com/index.php?page=dapi&s=tag&q=index&json=1&name_pattern=%tokidoki_bosotto_russia-go_de_dereru_tonari_no_alya-san%
GET https://gelbooru.com/index.php?page=dapi&s=tag&q=index&json=1&name_pattern=%tokidoki_bosotto%
